#import <AppKit/AppKit.h>

#include "macpasteboard.h"

using ClipboardBundle::Item;
using ClipboardBundle::ItemType;

static NSPasteboard* board(void* pasteboard)
{
    return (__bridge NSPasteboard*)pasteboard;
}

static QByteArray toBytes(NSData* data)
{
    return data ? QByteArray((const char*)data.bytes, (qsizetype)data.length) : QByteArray();
}

MacPasteboard::MacPasteboard(const QString& name)
{
    @autoreleasepool {
        NSPasteboard* pasteboard = name.isEmpty() ? [NSPasteboard generalPasteboard]
                                                  : [NSPasteboard pasteboardWithName:name.toNSString()];
        m_Pasteboard = (void*)CFBridgingRetain(pasteboard);
    }
}

MacPasteboard::~MacPasteboard()
{
    if (m_Pasteboard != nullptr) {
        CFRelease((CFTypeRef)m_Pasteboard);
    }
}

long MacPasteboard::changeCount() const
{
    @autoreleasepool {
        return (long)[board(m_Pasteboard) changeCount];
    }
}

bool MacPasteboard::hasSensitiveData() const
{
    @autoreleasepool {
        NSArray<NSPasteboardType>* types = [board(m_Pasteboard) types];
        for (NSString* marker in @[@"org.nspasteboard.ConcealedType",
                                   @"org.nspasteboard.TransientType",
                                   @"org.nspasteboard.AutoGeneratedType"]) {
            if ([types containsObject:marker]) {
                return true;
            }
        }
        return false;
    }
}

QVector<Item> MacPasteboard::read() const
{
    QVector<Item> items;
    @autoreleasepool {
        NSPasteboard* pasteboard = board(m_Pasteboard);
        if ([[pasteboard types] containsObject:NSPasteboardTypeFileURL]) {
            return items;
        }

        NSString* text = [pasteboard stringForType:NSPasteboardTypeString];
        if (text.length > 0) {
            items.append({ItemType::Text, QString::fromNSString(text).toUtf8().replace("\r\n", "\n")});
        }
        NSData* html = [pasteboard dataForType:NSPasteboardTypeHTML];
        if (html.length > 0) {
            items.append({ItemType::Html, toBytes(html)});
        }
        NSData* rtf = [pasteboard dataForType:NSPasteboardTypeRTF];
        if (rtf.length > 0) {
            items.append({ItemType::Rtf, toBytes(rtf)});
        }
        NSData* png = [pasteboard dataForType:NSPasteboardTypePNG];
        if (png.length == 0) {
            NSData* tiff = [pasteboard dataForType:NSPasteboardTypeTIFF];
            if (tiff.length > 0) {
                NSBitmapImageRep* rep = [NSBitmapImageRep imageRepWithData:tiff];
                png = [rep representationUsingType:NSBitmapImageFileTypePNG properties:@{}];
            }
        }
        if (png.length > 0) {
            items.append({ItemType::Png, toBytes(png)});
        }
    }
    return items;
}

long MacPasteboard::write(const QVector<Item>& items)
{
    @autoreleasepool {
        NSPasteboard* pasteboard = board(m_Pasteboard);
        [pasteboard clearContents];
        for (const Item& item : items) {
            NSData* data = [NSData dataWithBytes:item.data.constData() length:(NSUInteger)item.data.size()];
            switch (item.type) {
            case ItemType::Text:
                [pasteboard setString:QString::fromUtf8(item.data).toNSString() forType:NSPasteboardTypeString];
                break;
            case ItemType::Html:
                [pasteboard setData:data forType:NSPasteboardTypeHTML];
                break;
            case ItemType::Rtf:
                [pasteboard setData:data forType:NSPasteboardTypeRTF];
                break;
            case ItemType::Png:
                [pasteboard setData:data forType:NSPasteboardTypePNG];
                break;
            }
        }
        return (long)[pasteboard changeCount];
    }
}

void MacPasteboard::releaseForTests()
{
    @autoreleasepool {
        [board(m_Pasteboard) releaseGlobally];
    }
}
